paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  pages:
    path: ''
    output: true
    filter: strict
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default page:
        path:
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon: notes
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
_inputs:
  layout:
    type: text
    hidden: true
    cascade: true
  col-type:
    type: text
    hidden: true
    cascade: true
  block-content-html:
    type: html
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      center: text-center
      format: p h2 h3 a img
      horizontalrule: true
      image: true
      image_size_attributes: true
      left: text-left
      link: true
      right: text-right
      styles: /editor.css
    label: Content
    cascade: true
  min-height:
    type: select
    options:
      allow_empty: true
      values:
        50vh: half screen min-min
        75vh: three quater screen min-min
        90vh: just short of full screen
        100vh: full screen
    cascade: true
  text-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - center
        - right
    cascade: true
  desktop-image-position: 
    type: select
    options:
      allow_empty: false
      values:
        - left
        - right
  vert-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - top
        - middle
        - bottom
  vert-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - top
        - bottom
    cascade: true
  img_apsect:
    type: select
    options:
      allow_empty: false
      values:
        '1': Square
        9/16: tall Portraight
        4/5: Portraight
        5/4: Landscape
        16/9: wide Landscape
        initial: Images Native
    cascade: true
_structures:
  blocks:
    style: select
    values:
      - label: Simple banner
        value:
          _id: banner
          block-content-html: <p>dan was here :D</p>
          background-desktop-image: https://picsum.photos/id/1023/600/400
          background-mobile-image: https://picsum.photos/id/1024/600/400
          text-alignment: center
          vert-alignment: middle
          overlay-color: black
          overlay-opacity: 0.5
          min-height: 90vh
          top-space-padding: 10vw
          bottom-space-padding: 5vw
          color-scheme: dark
      - label: Split banner
        values: 
          _id: banner-split
          block-content-html: >-
            <p>dan was here :D</p><p></p><h2 class="larger-heading">And it was
            epic</h2>
          background-desktop-image: https://picsum.photos/id/1023/600/400
          background-mobile-image: https://picsum.photos/id/1024/600/400
          background-alt: bg-alt
          desktop-collapse-bg-padding: true
          desktop-image-position: right
          section-gap: 1rem
          text-alignment: center
          vert-alignment: bottom
          mobile-image-position: bottom
          mobile-collapse-bg-padding: false
          img_apsect: 1
          top-space-padding: 10vw
          bottom-space-padding: 5vw
          color-scheme: dark
      - label: Video banner
        value:
          _id: banner-video
          block-content-html: <p>dan was here :D</p>
          videos:
            - video_path: /uploads/sea-24216-360p.mp4
              video_type: mp4
          text-alignment: center
          vert-alignment: middle
          overlay-color: black
          overlay-opacity: 0.5
          min-height: 90vh
          top-space-padding: 10vw
          bottom-space-padding: 5vw
          color-scheme: dark
      - label: Grid
        value:
          _id: grid
          grid-desktop-columns: 4
          grid-mobile-columns: 2
          grid-gap: 1rem
          columns:
          color-scheme: dark
      - label: Accordion 
        value:
          _id: accordion
          block-content-html: <p>dan was here :D</p><p></p><h2>And it was epic</h2>
          drop_down:
            button-text: Where is dan
            icon_path: https://picsum.photos/id/1023/600/400
            icon_alt: bike
            block-content-html: <p>dan was here :D</p><p>dan was here :D</p><p>dan was here :D</p><p>dan was here :D</p>
          color-scheme: dark  
  columns:
    style: select
    values:
      - label: Image
        value:
          col-type: img
          image: https://picsum.photos/id/1023/600/400
          image_alt:
          img_apsect: 1
          col-width: 2
          col-height: 2
      - label: Text Block
        value:
          col-type: text
          block-content-html: <p>dan was here :D</p>
          icon-path:
          icon-alt:
          color-scheme: featured
          col-width: 1
          col-height: 1
      - label: video
        value:
          col-type: video
          videos: 
            - video_path: /uploads/sea-24216-360p.mp4
              video_type: mp4
          video_controls: false
          video_autoplay: true
          img_apsect: 4/5
          col-width: 1
# Snippet definitions are generic variables that can be referenced in snippets
# In this case, we're defining the common set of tokens that are relevant to
# Jekyll/liquid tags. (This covers things like the `=` symbol between keys and values)
# You shouldn't need to change these.
_snippets_definitions:
  jekyll_liquid_format:
    root_value_delimiter: '='
    root_pair_delimiter:
      - ''
    array_boundary:
      start: '['
      end: ']'
    array_delimiter: ','
    string_boundary:
      - '"'
      - ''''
    forbidden_tokens:
      - '%}'
      - '-%}'
      - '}}'
      - ','

# Snippet templates create a reusable structure to reduce repetition in snippets.
# These are what you normally import in cloudcannon using _snippets_imports
# As an example of creating one, here is a basic template for defining snippets that are liquid includes.

_snippets_templates:
  jekyll_liquid_include:
    snippet: '{% include [[name]] [[args]] %}'
    params:
      name:
        parser: literal
        options:
          literal:
            # This ref needs to be supplied by the _snippet when used
            ref: include_name
      args:
        parser: key_values
        options:
          models:
            # This ref needs to be supplied by the _snippet when used
            ref: named_args
          format:
             # This ref is pulled from the `_snippets_definitions` above
            ref: jekyll_liquid_format

# Snippets defines each editor-facing snippet.
# Here we inherit the above snippet, and specify the remaining `ref` variables.
_snippets:
  # figure:
  #   template: jekyll_liquid_include
  #   inline: false
  #   preview:
  #     text: Figure
  #   definitions:
  #     include_name: figure.html
  #     named_args:
  #       - editor_key: image
  #         type: string
  #       - editor_key: alt
  #         type: string
  #       - editor_key: caption_html
  #         type: string
  image_grid:
    template: jekyll_liquid_include
    inline: false
    preview:
      text: 3 image gallery
    definitions:
      include_name: snippets/imgGallery3.html
      named_args:
        - editor_key: first-image
          type: string
        - editor_key: first-alt
          type: string
        - editor_key: second-image
          type: string
        - editor_key: second-alt
          type: string
        - editor_key: third-image
          type: string
        - editor_key: third-alt
          type: string
        - editor_key: image_size_ratio
          type: string
  floating_image:
    template: jekyll_liquid_include
    inline: true
    preview:
      text: floating image
    definitions:
      include_name: snippets/image-float.html
      named_args:
        - editor_key: image
          type: string
        - editor_key: alt
          type: string
        - editor_key: float-direction
          type: string


data_config: {}
timezone: Etc/UTC
